services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: alfasoft-contact-list
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8081:80"
      # - "${APP_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - alfasoft-contact-list-network

  mariadb:
    image: mariadb:latest
    volumes:
      - ./docker/mysql/volumes/mysql:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "33:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_alfasoft_contact_list
      MYSQL_USER: db
      MYSQL_PASSWORD: password
    networks:
      - alfasoft-contact-list-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - alfasoft-contact-list-network

networks:
  alfasoft-contact-list-network:
    driver: bridge